apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-deployment
  labels:
    app: ctse-app
spec:
  replicas: 3 #number of instances in pods
  selector:
    matchLabels: # This must match the labels set on the pod
      app: ctse-app
  template:
    metadata:
      labels:
        app: ctse-app # Set labels on the pod.
    spec:
      containers:
        - name: ctse-app
          image: deshi97/ctse-assignment:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 6500
