apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctse-deployment
  labels:
    app: ctse-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cts-app
  template:
    metadata:
      labels:
        app: cts-app
    spec:
      containers:
        - name: ctse-app
          image: deshi97/ctse-assignment:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 6500
