apiVersion: v1
kind: Service
metadata:
  name: ctse-service
  labels:
    app: ctse-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 6500
  selector:
    app: ctse-app
  sessionAffinity: None
